Backed out changeset 7a55d41f8ca2 due to build bustage: c:/builds/slave/trunk_win2k3_hw/build/widget/src/windows/nsWindow.cpp(7353) : error C2446: '==' : no conversion from 'HWND' to 'HWND (__stdcall *)(void)'         There is no context in which this conversion is possible c:/builds/slave/trunk_win2k3_hw/build/widget/src/windows/nsWindow.cpp(7353) : error C2040: '==' : 'HWND (__stdcall *)(void)' differs in levels of indirection from 'HWND'